### ISSUE TITLE
Subclassing Window throws an error

### ISSUE THREAD

**Issue by typoman** [robotools/vanilla#109]
Hi All,
Why it's possible to subclass `Drawer` but not `FloatingWindow`? If I try to subclass the latter, I can't add any new methods. Consider the following for an example:

```
import vanilla

class test(vanilla.Drawer):

	def testMethod(self, arg1, arg2):
	    pass

class test(vanilla.FloatingWindow):

	def testMethod(self, arg1, arg2):
	    pass
```

I get this error for the `FloatingWindow` subclass:

```
Traceback (most recent call last):
  File "<untitled>", line 8, in <module>
objc.BadPrototypeError: Objective-C expects 1 arguments, Python argument has 3 arguments for <unbound selector testMethod of test at 0x115621880>
```

**Comment by typemytype** [comment]
A `Drawer` is a python object and a `FloatingWindow` is a NSObject...

it is possible to subclass a `FloatinWindow` but with some constrains:

* method names must have `_` underscore for each argument, so in your case: `def testMethodForArg1_arg1_(self, arg1, arg2):`
* you can only have one class declaration with the same name, during the same runtime. Best practise is to organise your nsObject subclasses in modules and import them, so there are registered only once.

good luck!!

**Comment by justvanrossum** [comment]
Or you use the objc.python_method decorator:

```python
import objc
import vanilla

class test(vanilla.FloatingWindow):

    @objc.python_method
    def testMethod(self, arg1, arg2):
        pass
```

When subclassing NSObject (which indeed you are here) be aware that it's good practice to use a prefix to make it more likely your classname is globally unique. Eg. `XYZFloatingWindowSublass`. This is because ObjC classes are global: you can't have two classes named "test" for example, not even in different modules.

While you're at it, you may need the `ClassNameIncrementer` metaclass while developing, but I forgot where it lives in RoboFont (perhaps it should be added to vanilla).

**Comment by gferreira** [comment]
`ClassNameIncrementer` lives in `lib.tools.debugTools`

**Comment by typemytype** [comment]
+1 to move this to vanilla, but I dont know where yet...

and for now vanilla itself is using `python_method` from `vanilla.py23` which is not the best option

**Comment by typoman** [comment]
Thank you so much for all your help! ( ͡° ͜ʖ ͡°)
